// <auto-generated />
using System;
using ExerciseService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExerciseService.Persistence.Migrations
{
    [DbContext(typeof(ExerciseDbContext))]
    [Migration("20260311094711_ExpandExerciseSeedData")]
    partial class ExpandExerciseSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExerciseService.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .HasColumnType("text");

                    b.Property<string>("Equipment")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("MuscleGroup")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Chest",
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Chest",
                            Name = "Incline Bench Press"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Chest",
                            Name = "Decline Bench Press"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Chest",
                            Name = "Dumbbell Bench Press"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Chest",
                            Name = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Cable",
                            IsPublic = true,
                            MuscleGroup = "Chest",
                            Name = "Cable Fly"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Chest",
                            Name = "Dumbbell Fly"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Chest",
                            Name = "Push Up"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Chest",
                            Name = "Chest Dip"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-00000000000a"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Machine",
                            IsPublic = true,
                            MuscleGroup = "Chest",
                            Name = "Machine Chest Press"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-00000000000b"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Machine",
                            IsPublic = true,
                            MuscleGroup = "Chest",
                            Name = "Pec Deck Machine"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-00000000000c"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Chest",
                            Name = "Landmine Press"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-00000000000d"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Chest",
                            Name = "Dumbbell Pullover"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-00000000000e"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Other",
                            IsPublic = true,
                            MuscleGroup = "Chest",
                            Name = "Svend Press"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-00000000000f"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Chest",
                            Name = "Diamond Push Up"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Back",
                            Name = "Pull Up"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Back",
                            Name = "Chin Up"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Cable",
                            IsPublic = true,
                            MuscleGroup = "Back",
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Back",
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Back",
                            Name = "Dumbbell Row"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Cable",
                            IsPublic = true,
                            MuscleGroup = "Back",
                            Name = "Seated Cable Row"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Advanced",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Back",
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Back",
                            Name = "T-Bar Row"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Cable",
                            IsPublic = true,
                            MuscleGroup = "Back",
                            Name = "Face Pull"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-00000000000a"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Back",
                            Name = "Hyperextension"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-00000000000b"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Advanced",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Back",
                            Name = "Pendlay Row"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-00000000000c"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Back",
                            Name = "Meadows Row"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-00000000000d"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Cable",
                            IsPublic = true,
                            MuscleGroup = "Back",
                            Name = "Straight Arm Pulldown"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-00000000000e"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Back",
                            Name = "Inverted Row"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-00000000000f"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Cable",
                            IsPublic = true,
                            MuscleGroup = "Back",
                            Name = "Single Arm Cable Row"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Shoulders",
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Shoulders",
                            Name = "Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Shoulders",
                            Name = "Arnold Press"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Shoulders",
                            Name = "Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Shoulders",
                            Name = "Front Raise"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Shoulders",
                            Name = "Reverse Fly"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Shoulders",
                            Name = "Upright Row"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Cable",
                            IsPublic = true,
                            MuscleGroup = "Shoulders",
                            Name = "Cable Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Machine",
                            IsPublic = true,
                            MuscleGroup = "Shoulders",
                            Name = "Machine Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-00000000000a"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Advanced",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Shoulders",
                            Name = "Behind The Neck Press"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-00000000000b"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Shoulders",
                            Name = "Lu Raise"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-00000000000c"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Cable",
                            IsPublic = true,
                            MuscleGroup = "Shoulders",
                            Name = "Cable Face Pull"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-00000000000d"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Shoulders",
                            Name = "Dumbbell Shrug"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-00000000000e"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Shoulders",
                            Name = "Barbell Shrug"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-00000000000f"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Other",
                            IsPublic = true,
                            MuscleGroup = "Shoulders",
                            Name = "Plate Front Raise"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Biceps",
                            Name = "Barbell Curl"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Biceps",
                            Name = "Dumbbell Curl"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Biceps",
                            Name = "Hammer Curl"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Biceps",
                            Name = "Preacher Curl"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Biceps",
                            Name = "Concentration Curl"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Cable",
                            IsPublic = true,
                            MuscleGroup = "Biceps",
                            Name = "Cable Curl"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Biceps",
                            Name = "EZ Bar Curl"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Biceps",
                            Name = "Incline Dumbbell Curl"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Biceps",
                            Name = "Spider Curl"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-00000000000a"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Biceps",
                            Name = "Reverse Curl"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-00000000000b"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Cable",
                            IsPublic = true,
                            MuscleGroup = "Biceps",
                            Name = "Bayesian Curl"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-00000000000c"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Biceps",
                            Name = "Zottman Curl"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Cable",
                            IsPublic = true,
                            MuscleGroup = "Triceps",
                            Name = "Tricep Pushdown"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Triceps",
                            Name = "Skull Crusher"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Triceps",
                            Name = "Tricep Dip"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Triceps",
                            Name = "Overhead Tricep Extension"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Triceps",
                            Name = "Close Grip Bench Press"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Triceps",
                            Name = "Tricep Kickback"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Cable",
                            IsPublic = true,
                            MuscleGroup = "Triceps",
                            Name = "Cable Overhead Extension"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Triceps",
                            Name = "Bodyweight Tricep Extension"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Advanced",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Triceps",
                            Name = "JM Press"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-00000000000a"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Triceps",
                            Name = "French Press"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-00000000000b"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Cable",
                            IsPublic = true,
                            MuscleGroup = "Triceps",
                            Name = "Rope Pushdown"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-00000000000c"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Triceps",
                            Name = "Bench Dip"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Legs",
                            Name = "Barbell Squat"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Advanced",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Legs",
                            Name = "Front Squat"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Machine",
                            IsPublic = true,
                            MuscleGroup = "Legs",
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Legs",
                            Name = "Romanian Deadlift"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Legs",
                            Name = "Lunge"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Legs",
                            Name = "Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Machine",
                            IsPublic = true,
                            MuscleGroup = "Legs",
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Machine",
                            IsPublic = true,
                            MuscleGroup = "Legs",
                            Name = "Leg Curl"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Machine",
                            IsPublic = true,
                            MuscleGroup = "Legs",
                            Name = "Calf Raise"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-00000000000a"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Legs",
                            Name = "Goblet Squat"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-00000000000b"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Machine",
                            IsPublic = true,
                            MuscleGroup = "Legs",
                            Name = "Hack Squat"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-00000000000c"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Legs",
                            Name = "Hip Thrust"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-00000000000d"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Advanced",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Legs",
                            Name = "Sumo Deadlift"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-00000000000e"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Legs",
                            Name = "Sissy Squat"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-00000000000f"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Machine",
                            IsPublic = true,
                            MuscleGroup = "Legs",
                            Name = "Seated Calf Raise"
                        },
                        new
                        {
                            Id = new Guid("a0000007-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Core",
                            Name = "Plank"
                        },
                        new
                        {
                            Id = new Guid("a0000007-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Core",
                            Name = "Russian Twist"
                        },
                        new
                        {
                            Id = new Guid("a0000007-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Core",
                            Name = "Hanging Leg Raise"
                        },
                        new
                        {
                            Id = new Guid("a0000007-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Cable",
                            IsPublic = true,
                            MuscleGroup = "Core",
                            Name = "Cable Crunch"
                        },
                        new
                        {
                            Id = new Guid("a0000007-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Other",
                            IsPublic = true,
                            MuscleGroup = "Core",
                            Name = "Ab Wheel Rollout"
                        },
                        new
                        {
                            Id = new Guid("a0000007-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Core",
                            Name = "Mountain Climber"
                        },
                        new
                        {
                            Id = new Guid("a0000007-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Core",
                            Name = "Dead Bug"
                        },
                        new
                        {
                            Id = new Guid("a0000007-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Cable",
                            IsPublic = true,
                            MuscleGroup = "Core",
                            Name = "Pallof Press"
                        },
                        new
                        {
                            Id = new Guid("a0000007-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Core",
                            Name = "Bicycle Crunch"
                        },
                        new
                        {
                            Id = new Guid("a0000007-0000-0000-0000-00000000000a"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Core",
                            Name = "Side Plank"
                        },
                        new
                        {
                            Id = new Guid("a0000007-0000-0000-0000-00000000000b"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Advanced",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Core",
                            Name = "Dragon Flag"
                        },
                        new
                        {
                            Id = new Guid("a0000007-0000-0000-0000-00000000000c"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Cable",
                            IsPublic = true,
                            MuscleGroup = "Core",
                            Name = "Woodchopper"
                        },
                        new
                        {
                            Id = new Guid("a0000008-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Machine",
                            IsPublic = true,
                            MuscleGroup = "Cardio",
                            Name = "Treadmill Run"
                        },
                        new
                        {
                            Id = new Guid("a0000008-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Machine",
                            IsPublic = true,
                            MuscleGroup = "Cardio",
                            Name = "Cycling"
                        },
                        new
                        {
                            Id = new Guid("a0000008-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Other",
                            IsPublic = true,
                            MuscleGroup = "Cardio",
                            Name = "Jump Rope"
                        },
                        new
                        {
                            Id = new Guid("a0000008-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Machine",
                            IsPublic = true,
                            MuscleGroup = "Cardio",
                            Name = "Rowing Machine"
                        },
                        new
                        {
                            Id = new Guid("a0000008-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Cardio",
                            Name = "Burpee"
                        },
                        new
                        {
                            Id = new Guid("a0000008-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Machine",
                            IsPublic = true,
                            MuscleGroup = "Cardio",
                            Name = "Stair Climber"
                        },
                        new
                        {
                            Id = new Guid("a0000008-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Other",
                            IsPublic = true,
                            MuscleGroup = "Cardio",
                            Name = "Battle Ropes"
                        },
                        new
                        {
                            Id = new Guid("a0000008-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Other",
                            IsPublic = true,
                            MuscleGroup = "Cardio",
                            Name = "Box Jump"
                        },
                        new
                        {
                            Id = new Guid("a0000008-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Machine",
                            IsPublic = true,
                            MuscleGroup = "Cardio",
                            Name = "Elliptical"
                        },
                        new
                        {
                            Id = new Guid("a0000008-0000-0000-0000-00000000000a"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Cardio",
                            Name = "High Knees"
                        },
                        new
                        {
                            Id = new Guid("a0000009-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Advanced",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Full Body",
                            Name = "Clean and Press"
                        },
                        new
                        {
                            Id = new Guid("a0000009-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Kettlebell",
                            IsPublic = true,
                            MuscleGroup = "Full Body",
                            Name = "Kettlebell Swing"
                        },
                        new
                        {
                            Id = new Guid("a0000009-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Advanced",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Full Body",
                            Name = "Thruster"
                        },
                        new
                        {
                            Id = new Guid("a0000009-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Advanced",
                            Equipment = "Kettlebell",
                            IsPublic = true,
                            MuscleGroup = "Full Body",
                            Name = "Turkish Get Up"
                        },
                        new
                        {
                            Id = new Guid("a0000009-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Advanced",
                            Equipment = "Barbell",
                            IsPublic = true,
                            MuscleGroup = "Full Body",
                            Name = "Snatch"
                        },
                        new
                        {
                            Id = new Guid("a0000009-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Advanced",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Full Body",
                            Name = "Man Maker"
                        },
                        new
                        {
                            Id = new Guid("a0000009-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Bodyweight",
                            IsPublic = true,
                            MuscleGroup = "Full Body",
                            Name = "Bear Crawl"
                        },
                        new
                        {
                            Id = new Guid("a0000009-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Advanced",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Full Body",
                            Name = "Devil Press"
                        },
                        new
                        {
                            Id = new Guid("a0000009-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Beginner",
                            Equipment = "Dumbbells",
                            IsPublic = true,
                            MuscleGroup = "Full Body",
                            Name = "Farmers Walk"
                        },
                        new
                        {
                            Id = new Guid("a0000009-0000-0000-0000-00000000000a"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Intermediate",
                            Equipment = "Kettlebell",
                            IsPublic = true,
                            MuscleGroup = "Full Body",
                            Name = "Kettlebell Clean"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
